// src/frameworks/react/App.js
import React, { Component } from "react";

class App extends Component {
  constructor(props) {
    super(props);
    this.state = { ...props.state, query: "" };
  }

  render() {
    const {
      state: { query, status, name, result },
      props: {
        commands: { load }
      }
    } = this;
    const onSubmit = evt => {
      evt.preventDefault();
      load(this.state.query);
    };
    const onChange = evt => {
      this.setState({ query: evt.target.value });
    };

    let mainResult;

    switch (status) {
      case "loading":
        mainResult = <p>loading...</p>;
        break;

      case "found result":
        mainResult = (
          <ul>
            {result._embedded.quotes.map(quote => (
              <li key={quote.value}>{quote.value}</li>
            ))}
          </ul>
        );
        break;

      default:
        mainResult = <p>{status || ""}</p>;
    }

    return (
      <div className="App">
        <h1>{name}</h1>
        <form onSubmit={onSubmit}>
          <input type="text" name="query" value={query} onChange={onChange} />
          <button>Search</button>
        </form>
        {mainResult}
      </div>
    );
  }
}

export default App;

// src/frameworks/vue/App.vue
<template>
  <div id="app">
    <h1>{{state.name}}</h1>
    <input v-model="query" />
    <button @click="search">Search</button>
    <p v-if="state.status==='loading'">loading...</p>
    <ul v-else-if="state.status==='found result'">
      <li
        v-for="quote in state.result._embedded.quotes"
        :key="quote.quote_id"
      >{{quote.value}}</li>
    </ul>
    <p v-else>{{state.status}}</p>
  </div>
</template>

<script>
export default {
  props: {
    state: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      query: ""
    };
  },
  name: "app",
  methods: {
    search() {
      this.state.commands.load(this.query);
    }
  }
};
</script>

<style>
html {
  height: 100%;
}

body {
  height: 100%;
  overflow: hidden;
}
</style>
